# Generated by Django 4.1.5 on 2023-01-16 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contacts",
            old_name="email",
            new_name="myemail",
        ),
        migrations.RenameField(
            model_name="contacts",
            old_name="name",
            new_name="mypassword",
        ),
        migrations.RemoveField(
            model_name="contacts",
            name="date",
        ),
        migrations.RemoveField(
            model_name="contacts",
            name="desc",
        ),
        migrations.RemoveField(
            model_name="contacts",
            name="phone",
        ),
    ]
