# Generated by Django 4.1.5 on 2023-01-16 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_rename_email_contacts_myemail_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contacts",
            new_name="Contactus",
        ),
    ]
